http:
  protocol: "HTTPS"
  host: "mule-web-api-purchases-paf9yo.5sc6y6-1.usa-e2.cloudhub.io"
  producthost: "mule-web-api-baotdn2-paf9yo.5sc6y6-4.usa-e2.cloudhub.io"
  port: "8081"
  portproduct: "8081"
  connections: "6"
  productbase: "products/v1"
  purchasebase: "purchases/v1"
  
db:
  mls-mysql:
    host: "mysql-192747-0.cloudclusters.net"
    port: "10046"
    user: "admin"
    password: "![XMfqEHYdIdZBuL0/GeHKIA==]"
    purchase-order-table: "MLSDB_BaoTDN2.PurchaseOrders"
    purchase-detail-order-table: "MLSDB_BaoTDN2.PurchaseOrderDetails"