http:
  protocol: "HTTPS"
  host: "mule-web-api-baotdn2-paf9yo.5sc6y6-4.usa-e2.cloudhub.io"
  port: "8081"
  supportPort: "8082"
  connections: "6"
  productbase: "products/v1"
  
db:
  mls-mysql:
    host: "mysql-193237-0.cloudclusters.net"
    port: "10086"
    user: "admin"
    password: "![6qDrPCcetDMX1ys9WRKriA==]" 
    product-table: "MLSDB_BaoTDN2.Products"

sftp:
  mls:
    directory: "Products"
    host: "ap-southeast-1.sftpcloud.io"
    port: "22"
    username: "2b87139c38334b0d9a571dd162d39167"
    password: "![cpuqh3pJkrZ78VokhmLxfGANvIxjIaT2MLsIXlngLJaxp3UcogKkaxxna/mbJ5no]"